#!/bin/tcsh -f

#######################################################################
# dar - disk archive - a backup/restoration program
# Copyright (C) 2002-2020 Denis Corbin
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# to contact the author : http://dar.linux.free.fr/email.html
#######################################################################

if(! -f configure) then
  echo "run this script from the root directory of CVS working directory"
  echo "which is where the 'configure' script resides"
  exit 1
endif

if("$1" == "") then
   echo "usage: $0 <version> {win32|win64} [options to dar]"
   exit
endif

if("$2" != "win32" && "$2" != "win64") then
   echo "unknown windows flavor"
   exit
endif

setenv MAKE_OPT "$3 $4 $5 $6 $7 $8 $9 ${10}"

# misc/make_cygwin_dist $1 ""
# misc/make_cygwin_dist $1 $2 "32" --enable-mode=32
misc/make_cygwin_dist $1 $2 "64" --enable-mode=64
