#!/bin/tcsh -f

if(! -f configure) then
  echo "run this script from the root directory of CVS working directory"
  echo "which is where the 'configure' script resides"
  exit 1
endif

if ("$1" == "") then
  echo "usage: $0 <archive>"
  exit
endif

misc/make_rpm $1 misc/dar.rpm.spec
mkdir rpm_dar
mv *.rpm rpm_dar
# misc/make_rpm $1 misc/dar32.rpm.spec
# mkdir rpm_dar32
# mv *.rpm rpm_dar32
misc/make_rpm $1 misc/dar64.rpm.spec
mkdir rpm_dar64
mv *.rpm rpm_dar64
