#!/bin/tcsh -f

#######################################################################
# dar - disk archive - a backup/restoration program
# Copyright (C) 2002-2023 Denis Corbin
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# to contact the author, see the AUTHOR file
#######################################################################

if(! -f configure) then
  echo "run this script from the root directory of CVS working directory"
  echo "which is where the 'configure' script resides"
  exit 1
endif

if ("$1" == "") then
  echo "usage: $0 <archive>"
  exit
endif

misc/make_rpm $1 misc/dar_ea.rpm.spec
mkdir rpm_dar_ea
mv *.rpm rpm_dar_ea
# misc/make_rpm $1 misc/dar32_ea.rpm.spec
# mkdir rpm_dar32_ea
# mv *.rpm rpm_dar32_ea
misc/make_rpm $1 misc/dar64_ea.rpm.spec
mkdir rpm_dar64_ea
mv *.rpm rpm_dar64_ea
