#!/bin/tcsh -f

if(! -f configure) then
  echo "run this script from the root directory of CVS working directory"
  echo "which is where the 'configure' script resides"
  exit 1
endif

if("$1" == "") then
   echo "usage: $0 <version> {win32|win64}"
   exit
endif

if("$2" != "win32" && "$2" != "win64") then
   echo "unknown windows flavor"
   exit
endif

# misc/make_cygwin_dist $1 ""
# misc/make_cygwin_dist $1 $2 "32" --enable-mode=32
misc/make_cygwin_dist $1 $2 "64" --enable-mode=64
