#!/bin/tcsh -f
# this script changes the dates of autoconf and automake configuration files
# as if they had just been compiled (this avoids the need of automake and
# autoconf when just a mix in the dates occured, as usual with CVS)

if(! -f configure) then
  echo "run this script from the root directory of CVS working directory"
  echo "which is where the 'configure' script resides"
  exit 1
endif

find . -name "Makefile.am" -exec touch {} \;
sleep 1
touch configure.ac
sleep 1
touch aclocal.m4
sleep 1
touch configure
sleep 1
find . -name "Makefile.in" -exec touch {} \;
sleep 1
touch config.h.in
