#!/bin/sh

if [ ! -f AUTHORS ] ; then
  echo "Script must be ran from the package root directory"
  exit 1
fi

cp src/build/configure.ac .
cp src/build/Makefile.am .

libtoolize --automake
gettextize --force
po/generate_POTFILES.in
aclocal -I m4
autoconf
autoheader
automake --add-missing --gnu

cp src/build/ChangeLog .
chmod a-w configure.ac Makefile.am ChangeLog
if [ ! -e mkinstalldirs ]; then
cp src/build/mkinstalldirs .
fi



