.TH DAR_CP 1 "OCT 4, 2003"
.UC 8
.SH NAME
dar_cp \- disk archive copy
.SH SYNOPSIS
.B dar_cp <source file> <destination file>
.P
.B dar_cp -h
.P
.B dar_cp -V
.SH DESCRIPTION
.B dar_cp
is similar to the standard 'cp' command, except it does not stop copying when an I/O error is met. Instead, it skips a bit further and continues to copy the rest of the file, as much as possible.

.PP
.B dar_cp
only accepts full filename (not directory) as argument. The reason of its
existence in dar package is that you need it if you use Parchive with dar
and have a corruption on a CD-R or any other read-only medium. You need to copy
the corrupted slice on a read-write filesystem, for Parchive be able to repair
it using slice associated redundancy files.

.SH OPTIONS

.PP
.TP 20
-h
Displays help usage.
.TP 20
-V
Displays version information.

.SH EXIT CODES
.B dar_cp exists with the following codes:
.TP 10
0
upon normal execution (be some corrupted parted skipped or not)
.TP 10
1
syntax error on command-line
.TP 10
2
could not open source or destination files
.TP 10
3
any other system error met during the copy

.SH SEE ALSO
dar(1), dar_xform(1), dar_manager(1), dar_slave(1)

.SH KNOWN BUGS
None actually.

.SH AUTHOR
.nf
http://dar.linux.free.fr/
Denis Corbin (dar.linux@free.fr)
France
Europe
