.TH DAR_XFORM 1 "SEPT 28, 2002"
.UC 8
.SH NAME
dar_xform \- disk archive "re-slicer"
.SH SYNOPSIS
.B dar_xform [options] [<path>/]source [<path>/]destination
.P
.B dar_xform -h
.P
.B dar_xform -V
.SH DESCRIPTION
.B dar_xform
changes the size of slices of an existing archive.
.PP
Source is the basename of the existing archive, destination is the basename of the archive to be created. If source basename is "-", the archive is read from standard input. If the destination basename is "-", the archive is written to standard output and -s option is not available.

.SH OPTIONS

.PP
.TP 20
-h
displays help usage.
.TP 20
-V
displays version information.
.TP 20
-b
make the terminal ring when user interaction is required (like for example the creation of a new slice when using the -p option)
.TP 20
-s <number>
Size of the slices in bytes. If the number is followed by k (or K), M, G, T or P the size is in kilobytes, megabytes, gigabytes, terabytes or petabytes respectively. Example: by default "20M" means 20 megabytes it is the same as giving 20971520 as argument (see also -aSI and -abinary options). If -s is not present the backup will be written to a single slice whatever the size of the backup may be (there is probably some filesystem limitation, thus you might expect problems with file size over 2 gigabytes, depending on your filesystem).
.TP 20
-S <number>
-S gives the size of the first slice which may be chosen independently of the size of following slices. This option needs -s and by default, the size of the first slice is the same as the one of the following slices.
.TP 20
-p
pauses before writing to a new slice (this requires -s). By default there is no pause, all slices are output in the same directory, up to the end of the backup or until the filesystem is full. In this later case, the user is informed of the lack of disk space and dar stops for user interaction. As soon as some disk space is available, the user can continue the backup.
.TP 20
-n
Do not allow overwriting of any slice.
.TP 20
-w
Do not warn before overwriting slice. By default (no -n and no -w) overwriting is allowed but a warning is issued before proceeding.
.TP 20
-E <string>
the string is a command-line to be launched between the slices of the destination archive. See dar(1) man page (same option) for more informations.
.TP
-F <string>
the string is a command-line to be launched between the slices of the source archive. See dar(1) man page (same option) for more informations.
.TP 20
-aSI[-unit[s]]
when using k M G T E Z Y prefixes to define a size, use the SI meaning: multiple of 10^3 (a Mega is 1,000,000).
.TP 20
-abinary[-unit[s]]
when using k M G T E Z Y prefixes to define a size, use the historical computer science meaning: multiple of 2^10  (a Mega is 1,048,576).
.P
-aSI and -abinary can be used several times, they affect all prefix which follow even those found in file included by -B option up to the next -a... occurrence. Note that if in a file included by -B option an -abinary or -aSI is met, it affects all the following prefix even those outside the included files (for example in the following "-B some.dcf -s 1K" 1K may be equal to 1000 or 1024 depending on the presence of an -aSI or -abinary in the file some.dcf. By default (before any -aSI/binary argument has been reached), binary interpretation of suffix is done (for compatibility with older versions).
.TP 20
-Q
Do not display any message on stderr when not launched from a terminal (for example when launched from an at job or crontab). Remains that any question to the user will be assumed a 'no' answer, which most of the time will abort the program.
.TP 20
-j
when virtual memory is exhausted, as user to make room before trying to continue. By default, when memory is exhausted dar aborts.

.SH NOTES
Dar is not concerned by scrambling. It does not need to be aware of it to be able to change the slice scheme. Thus, it is not able to scramble a clear archive or unscramble an already scrambled archive.

.SH EXIT CODES

.B dar_xform
uses the same exit status as dar does, see dar(1) man page.

.SH SEE ALSO
dar(1), dar_slave(1), dar_manager(1), dar_cp(1)

.SH KNOWN BUGS
None actually.

.SH AUTHOR
.nf
http://dar.linux.free.fr/
Denis Corbin (dar.linux@free.fr)
France
Europe
