.TH DAR_XFORM 1 "MAY 2, 2002"
.UC 8
.SH NAME
dar_xform \- disk archive "re-slicer"
.SH SYNOPSIS
.B dar_xform [options] [<path>/]source [<path>/]destination
.P
.B dar_xform -h
.P
.B dar_xform -V
.SH DESCRIPTION
.B dar_xform  
changes the size of slices of an existing archive.
.PP
Source is the basename of the existing archive, destination is the basename of the archive to be created. If source basename is "-", the archive is read from standard input. If the destination basename is "-", the archive is written to standard output and (-s option) is not available.

.SH OPTIONS

.PP
.TP 20
-h
displays help usage.
.TP 20
-V 
displays version information.
.TP 20
-b 
make the terminal ring when user interaction is required (like for example the creation of a new slice when using the -p option)
.TP 20
-s <number>
Size of the slices in bytes. If the number is followed by k (or K), M, G, T or P the size is in kilobytes, megabytes, gigabytes, terabytes or petabytes respectively. Example: "20M" means 20 megabytes it is the same as giving 20971520 as argument. If -s is not present the backup will be written to a single slice whatever the size of the backup may be (there is probably some filesystem limitation, thus you might expect problems with file size over 2 gigabytes, depending on your filesystem).
.TP 20
-S <number>
-S gives the size of the first slice which may be chosen independently of the size of following slices. This option needs -s and by default, the size of the first slice is the same as the one of the following slices.
.TP 20
-p 
pauses before writing to a new slice (this requires -s). By default there is no pause, all slices are output in the same directory, up to the end of the backup or until the filesystem is full. In this later case, the user is informed of the lack of disk space and dar stops for user interaction. As soon as some disk space is available, the user can continue the backup.
.TP 20
-n
Do not allow overwriting of any slice.
.TP 20
-w
Do not warn before overwriting slice. By default (no -n and no -w) overwriting is allowed but a warning is issued before proceeding.

.SH EXIT CODES

.B dar_xform
uses the same exit status as dar does, see dar(1) man page.

.SH SEE ALSO
dar(1), dar_slave(1)

.SH KNOWN BUGS
None actually.

.SH AUTHOR
.nf
http://dar.linux.free.fr/
Denis Corbin (dar.linux@free.fr)
France
Europe
