#!/bin/sh
#######################################################################
# dar - disk archive - a backup/restoration program
# Copyright (C) 2002-2024 Denis Corbin
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# to contact the author, see the AUTHOR file
#######################################################################

if [ -z "$1" -o -z "$2" -o ! -z "$3" ] ; then
   echo "usage: $0 <src> <dst>"
   exit 1
fi

TMP_SRC=dar_install_cp_test_src
TMP_DST=dar_install_cp_test_dst

if mkdir "$TMP_DST" && mkdir "$TMP_SRC" ; then
  if cp -dR --preserve=mode $TMP_SRC $TMP_DST 1> /dev/null 2> /dev/null ; then
     rm -rf "$TMP_SRC" "$TMP_DST"
     exec cp -dR --preserve=mode "$1" "$2"
  else
     # BSD-like Unix that does not support -d or --preserve options
     rm -rf "$TMP_SRC" "$TMP_DST"
     exec cp -pR "$1" "$2"
  fi
else
  rm -rf "$TMP_SRC" "$TMP_DST"
  echo "Impossible to create $TMP_DST or $TMP_SRC in order to determine capabilities of the 'cp' command"
  exit 2
fi
