#!/bin/bash

#######################################################################
# dar - disk archive - a backup/restoration program
# Copyright (C) 2002-2024 Denis Corbin
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# to contact the author, see the AUTHOR file
#######################################################################

if [ -z "$1" -o -z "$2" ] ; then
  echo "usage: $0 <FTP URL> <pattern>"
  echo "will remove pattern in the directory pointed to by the URL"
  exit 1
fi

script="_$2"
echo "script = $script"

echo "$1" | sed -r -n -e 's#^ftp://([^:@/]+):([^:@/]+)@([^:@/]+)(.*)$#ftp -n<<EOF\nopen \3\nuser \1 \2\npassive\nprompt\ncd \4\n#p' > "$script"

echo "mdelete $2" >> "$script"
echo "EOF" >> "$script"

source "$script"
rm "$script"

