#!/bin/bash

#######################################################################
# dar - disk archive - a backup/restoration program
# Copyright (C) 2002-2024 Denis Corbin
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# to contact the author, see the AUTHOR file
#######################################################################

if [ -z "$1" -o -z "$2" ] ; then
  echo "usage: $0 <SFTP URL> <pattern>"
  echo "will remove pattern in the directory pointed to by the URL"
  exit 1
fi

script="=$2"
echo "script = $script"

echo "$1" | sed -r -n -e 's#^sftp://([^:@/]+):([^:@/]+)@([^:@/]+)(.*)$#spawn sftp \1@\3\nexpect "*password:"\nsend "\2\\n"\nexpect "sftp>"\nsend \"cd \4\\n"#p' > "$script"
echo "expect 'sftp>'" >> "$script"
echo "send \"rm $2\\n\"" >> "$script"
echo "expect 'sftp>'" >> "$script"
echo "send \"exit\\n\"" >> "$script"
cat "$script"

expect -f "$script"
rm "$script"

