/*********************************************************************/
// dar - disk archive - a backup/restoration program
// Copyright (C) 2002-2026 Denis Corbin
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
// to contact the author, see the AUTHOR file
/*********************************************************************/

    /// \file header.hpp
    /// \brief slice header structure is defined here
    /// \ingroup Private


#ifndef HEADER_HPP
#define HEADER_HPP

#include "../my_config.h"

#include "infinint.hpp"
#include "generic_file.hpp"
#include "user_interaction.hpp"
#include "tlv_list.hpp"
#include "label.hpp"
#include "slice_layout.hpp"

namespace libdar
{

	/// \addtogroup Private
	/// @{

    const U_32 SAUV_MAGIC_NUMBER = 123; // Why "SAUV_..." because SAUV was the name of DAR much before its first release :-)

    using magic_number = U_32;

    enum flag_type
    {
	flag_type_terminal = 'T',
	flag_type_non_terminal = 'N',
	flag_type_located_at_end_of_slice = 'E' // since archive format version 8
    };


	/// this class manages the header of each slice

	/// this class was a struct before release 2.4.0, now promoted
	/// to a class it hides the fields and uses TLV to store the
	/// fields in the archive. This makes the header easier to
	/// extend by adding new fields, while letting a chance for the
	/// old implementation to be able to use more recent archives
	/// the main use of TLV is to handle optional fields easily.

    class header
    {
    public:
	    // constructors & Co.

        header() { clear(); };
        header(const header & ref) = default;
	header(header && ref) noexcept = default;
        header & operator = (const header & ref) = default;
	header & operator = (header && ref) noexcept = default;
	~header() = default;

	    // global methods

        void read(user_interaction & ui,
		  generic_file & f,
		  bool lax = false);
        void write(user_interaction &,  ///< user interaction for messages when necessary
		   generic_file & f,    ///< where to write down the header
		   bool with_header_size = false) const; ///< whether to also write down the slice header size info


	    /// resets the object
	void clear();

	    /// check is this is a valid first header to open

	    /// \param[in] dialog for user interaction
	    /// \param[in] slice_num slice number of the slic the header has been read from (set to zero for external slice header)
	    /// \param[in] initial whether this is the first time a header is validated for this slice set
	    /// \note throw Erange exception in case of invalidity
	void check_validity(user_interaction & dialog,
			    const infinint & slice_num,
			    bool initial) const;


	    /// check whether the given argument is part of the same slice set as current header

	    /// \note throw exception in case not of the same slice set
	void check_same_slice_set(const header & ref) const;


	    /// minimal size of a header in an archive

	    /// \return min size of a header once stored in an archive
	    /// \note since release 2.4.0 the header used for each slice is exactly the same.
	    /// before this release the header of the first slice might be bigger, it was known that
	    /// the size of the other header was "min_size" this let dar be able to find the proper
	    /// slice for a given position. For compatibility with older DAR format, it is thus important
	    /// to not change the value returned by this class method. This call is only used
	    /// when reading archive generated by old versions of dar < 2.4.0. (aka archive format <= 7)
        static U_I min_size() { return sizeof(magic_number) + label::common_size() + 2*sizeof(char); };


	    // fields access methods

	const magic_number & get_magic() const { return magic; };
	void set_magic(const magic_number & ref) { magic = ref; };

	const label & get_internal_name() const { return internal_name; };
	void set_internal_name(const label & ref) { internal_name = ref; };

	const char & get_flag() const { return flag; };
	void set_flag(const char & ref) { flag = ref; };

	const label & get_data_name() const { return data_name; };
	void set_data_name(const label & ref) { data_name = ref; };

	const infinint & get_first_slice_size() const { return sly.first_size; };
	void set_first_slice_size(const infinint & size) { sly.first_size = size; };

	const infinint & get_slice_size() const { return sly.other_size; };
	void set_slice_size(const infinint & size) { sly.other_size = size; };

	bool get_format_07_compatibility() const { return sly.older_sar_than_v8; };
	void set_format_07_compatibility(bool val = true) { sly.older_sar_than_v8 = val; };

	const infinint & get_common_slice_header_size() const { return sly.other_slice_header; };
	void set_common_slice_header_size(const infinint & size) { sly.other_slice_header = size; };

	const infinint & get_first_slice_header_size() const { return sly.first_slice_header; };
	void set_first_slice_header_size(const infinint & size) { sly.first_slice_header = size; };

	const slice_layout & get_slice_layout() const { return sly; };

	bool has_header_tlv() const { return header_tlv; };

    private:
        magic_number magic;    ///< constant string for all Dar archives
        label internal_name;   ///< constant string for all slices of a given archive (computed based on date and pid)
	label data_name;       ///< constant string for a set of data (constant with dar_xform, used to link isolated catalogue to its original data)
        char flag;             ///< whether slice is the last of the archive or not
	slice_layout sly;      ///< slicing information
	bool header_tlv;       ///< whether the header contains information on header sizes

	void fill_from(user_interaction & ui, const tlv_list & list);
	tlv_list build_tlv_list(user_interaction & ui, bool with_header_size) const;
    };

	/// @}

} // end of namespace

#endif

